# .github/workflows/ghcr.yml
name: Docker Publish to GHCR

on:
  workflow_run:
    workflows: ["Rust CI"] # rust.yml の name を指定
    types:
      - completed

# --- concurrency 設定を追加 ---
concurrency:
  # グループ名をワークフロー名と参照 (ブランチ名やタグ名) で定義
  # これにより、同じブランチ/タグに対する実行は同時に1つだけになる
  group: ${{ github.workflow }}-${{ github.ref }}
  # 同じグループで新しい実行が開始されたら、進行中の実行をキャンセルする
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Rust CI ワークフローが成功した場合のみ実行
    permissions:
      contents: read
      packages: write # ghcr.io への書き込み権限
      actions: write # 追加: キャッシュの書き込み権限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64 # マルチアーキテクチャビルド
          push: true
          tags: | # 修正: metadata-action のタグと latest タグを両方使う
            ${{ steps.meta.outputs.tags }}
            ghcr.io/${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          # --- キャッシュ設定を追加 ---
          cache-from: type=gha
          cache-to: type=gha,mode=max
