# .github/workflows/rust.yml
name: Rust CI

on:
  push:
    branches: [ "main" ] # mainブランチへのpush時に実行
  pull_request:
    branches: [ "main" ] # mainブランチへのpull request時にも実行

env:
  CARGO_TERM_COLOR: always # Cargoの出力をカラーにする

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest # 実行環境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # リポジトリをチェックアウト

    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable # 安定版のRustツールチェインをセットアップ
      with:
        toolchain: stable # 使用するツールチェイン (stable, beta, nightlyなど)

    - name: Cache dependencies
      uses: actions/cache@v4 # 依存関係をキャッシュしてビルド時間を短縮
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/ # targetディレクトリもキャッシュ (パスを修正)
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} # キャッシュキー

    - name: Build
      run: cargo build --verbose # ビルド実行

    - name: Run tests
      run: cargo test --verbose # テスト実行
